import { PrismaClient } from '../generated/prisma';
import { randomUUID } from 'crypto';

const prisma = new PrismaClient();

const ingredients: { id: string; name: string }[] = [
    { name: 'Salt', id: randomUUID() },
    { name: 'Black Pepper', id: randomUUID() },
    { name: 'Olive Oil', id: randomUUID() },
    { name: 'Garlic', id: randomUUID() },
    { name: 'Onion', id: randomUUID() },
    { name: 'Butter', id: randomUUID() },
    { name: 'Tomato', id: randomUUID() },
    { name: 'Basil', id: randomUUID() },
    { name: 'Parsley', id: randomUUID() },
    { name: 'Oregano', id: randomUUID() },
    { name: 'Paprika', id: randomUUID() },
    { name: 'Cumin', id: randomUUID() },
    { name: 'Coriander', id: randomUUID() },
    { name: 'Chili Powder', id: randomUUID() },
    { name: 'Cinnamon', id: randomUUID() },
    { name: 'Nutmeg', id: randomUUID() },
    { name: 'Thyme', id: randomUUID() },
    { name: 'Rosemary', id: randomUUID() },
    { name: 'Bay Leaf', id: randomUUID() },
    { name: 'Ginger', id: randomUUID() },
    { name: 'Lemon', id: randomUUID() },
    { name: 'Lime', id: randomUUID() },
    { name: 'Honey', id: randomUUID() },
    { name: 'Vinegar', id: randomUUID() },
    { name: 'Soy Sauce', id: randomUUID() },
    { name: 'Worcestershire Sauce', id: randomUUID() },
    { name: 'Ketchup', id: randomUUID() },
    { name: 'Mustard', id: randomUUID() },
    { name: 'Mayonnaise', id: randomUUID() },
    { name: 'Yogurt', id: randomUUID() },
    { name: 'Milk', id: randomUUID() },
    { name: 'Cream', id: randomUUID() },
    { name: 'Cheddar Cheese', id: randomUUID() },
    { name: 'Mozzarella', id: randomUUID() },
    { name: 'Parmesan', id: randomUUID() },
    { name: 'Egg', id: randomUUID() },
    { name: 'Chicken Breast', id: randomUUID() },
    { name: 'Ground Beef', id: randomUUID() },
    { name: 'Pork Loin', id: randomUUID() },
    { name: 'Salmon', id: randomUUID() },
    { name: 'Tuna', id: randomUUID() },
    { name: 'Shrimp', id: randomUUID() },
    { name: 'Rice', id: randomUUID() },
    { name: 'Pasta', id: randomUUID() },
    { name: 'Quinoa', id: randomUUID() },
    { name: 'Lentils', id: randomUUID() },
    { name: 'Black Beans', id: randomUUID() },
    { name: 'Chickpeas', id: randomUUID() },
    { name: 'Flour', id: randomUUID() },
    { name: 'Sugar', id: randomUUID() },
    { name: 'Brown Sugar', id: randomUUID() },
    { name: 'Baking Powder', id: randomUUID() },
    { name: 'Baking Soda', id: randomUUID() },
    { name: 'Vanilla Extract', id: randomUUID() },
    { name: 'Coconut Milk', id: randomUUID() },
    { name: 'Coconut Oil', id: randomUUID() },
    { name: 'Peanut Butter', id: randomUUID() },
    { name: 'Almonds', id: randomUUID() },
    { name: 'Walnuts', id: randomUUID() },
    { name: 'Cashews', id: randomUUID() },
    { name: 'Raisins', id: randomUUID() },
    { name: 'Dates', id: randomUUID() },
    { name: 'Apples', id: randomUUID() },
    { name: 'Bananas', id: randomUUID() },
    { name: 'Strawberries', id: randomUUID() },
    { name: 'Blueberries', id: randomUUID() },
    { name: 'Spinach', id: randomUUID() },
    { name: 'Broccoli', id: randomUUID() },
    { name: 'Carrot', id: randomUUID() },
    { name: 'Cucumber', id: randomUUID() },
    { name: 'Zucchini', id: randomUUID() },
    { name: 'Bell Pepper', id: randomUUID() },
    { name: 'Mushrooms', id: randomUUID() },
    { name: 'Potatoes', id: randomUUID() },
    { name: 'Sweet Potatoes', id: randomUUID() },
    { name: 'Corn', id: randomUUID() },
    { name: 'Peas', id: randomUUID() },
    { name: 'Avocado', id: randomUUID() },
    { name: 'Eggplant', id: randomUUID() },
    { name: 'Cabbage', id: randomUUID() },
    { name: 'Cauliflower', id: randomUUID() },
    { name: 'Green Beans', id: randomUUID() },
    { name: 'Celery', id: randomUUID() },
    { name: 'Leek', id: randomUUID() },
    { name: 'Asparagus', id: randomUUID() },
    { name: 'Beets', id: randomUUID() },
    { name: 'Radish', id: randomUUID() },
    { name: 'Pumpkin', id: randomUUID() },
    { name: 'Butternut Squash', id: randomUUID() },
    { name: 'Coconut', id: randomUUID() },
    { name: 'Pineapple', id: randomUUID() },
    { name: 'Mango', id: randomUUID() },
    { name: 'Orange', id: randomUUID() },
    { name: 'Grapes', id: randomUUID() },
    { name: 'Kiwi', id: randomUUID() },
    { name: 'Watermelon', id: randomUUID() },
    { name: 'Chili Pepper', id: randomUUID() },
    { name: 'Mint', id: randomUUID() },
    { name: 'Sage', id: randomUUID() },
    { name: 'Dill', id: randomUUID() },
    { name: 'Chives', id: randomUUID() },
];

async function main() {
    await prisma.ingredient.createMany({
        data: ingredients,
        skipDuplicates: true,
    });
    console.log('🌱 Seeded ingredients');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
